apiVersion: v1
kind: Pod
metadata:
  labels:
    description: mysql-pod
spec:
  containers:
  #mysql-client
  - name: mysql-client
    image: mysql:5.7
    resources:
      limits:
        memory: 256Mi
    command:
    - cat
    tty: true
  #mysql-server
  - name: mysql-server
    image: registry.access.redhat.com/rhscl/mariadb-102-rhel7:1
    resources:
      limits:
        memory: 256Mi
    env:
    - name: MYSQL_USER
      value: test
    - name: MYSQL_PASSWORD
      value: test
    - name: MYSQL_DATABASE
      value: testDB
    - name: MYSQL_ROOT_PASSWORD
      value: secret
    readinessProbe:
      tcpSocket:
        port: 3306
    initialDelaySeconds: 5
